name: 🚀 Build

on:
  push:
    workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: |
          npm ci
          npm i -g @vercel/ncc
          npm run build

      - name: Zip dist files
        id: pack
        uses: ./
        with:
          files: dist, action.yml

      - name: ⚙️ Unzip dist files
        run: |
          mkdir TODEPLOY
          unzip ${{ steps.pack.outputs.archive }} -d TODEPLOY

      - name: ⚙️ Parse version string
        id: version
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.pack.outputs.version }}

      - name: 📢 Publish dist files to dist branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          BRANCH: v${{ steps.version.outputs.major }}
          FOLDER: TODEPLOY
          SKIP_EMPTY_COMMITS: true
