name: 🚀 Build

on:
  push:
    branches:
      - main
    workflow_dispatch: {}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: |
          npm ci
          npm i -g @vercel/ncc
          npm run build

      - name: Zip dist files
        id: pack
        uses: ./
        with:
          files: dist, action.yml
